(define (cube x) (* x x x))

(define (p x) (- (* 3 x) (* 4 (cube x))))

(define (sine angle)
  (if (not (> (abs angle) 0.1))
      angle
      (p (sine (/ angle 3.0)))))

#| Exercise 1.15.a
    How many times is the procedure p applied when (sine 12.15)
    is evaluated?
|#

(sine 12.15)

#|
    (sine 12.15) is evaluated as many times as it takes until
    the argument / 3 <= 0.1
    12.5 / (3^4) = 0.15
    12.5 / (3^5) = 0.05

    The fifth time the condition in the if statement is met.
|#



#| Exercise 1.15.b
    What is the order of growth in space and number of steps
    (as a function of a) used by the process generated by the
    sine procedure when (sine a) is evaluated?
|#

#|
    At each evaluation of sine, sine is called at most 1 time.
    Meaning the growth in space is the same as the growth in
    steps.

    The growth rate of the number of steps is O(log a). (The
    base of 3 can be omitted)

    The exact formula for the number of steps taken is
    ceil(max(0, log_3(|a|/0.1) ))
|#